### ISSUE TITLE
Exclude setting "async-std" and "tokio" features at the same time.

### ISSUE THREAD

**Issue by luukvanderduim** [odilia-app/atspi#164]
In `atspi/src/lib.rs`
https://github.com/odilia-app/atspi/blob/c3338f4373ca5c0240e7dc9d3fddf832e102ecaf/atspi/src/lib.rs#L10C1-L11C89

```Rust
#[cfg(all(not(feature = "async-std"), not(feature = "tokio")))]
compile_error!("You must specify at least one of the `async-std` or `tokio` features.");
```
This warns us when neither "async-std" or "tokio" is set.

What about having both set?
This could easily happen I were to 

```toml
[dependencies]
atspi = { version = "0.22", features = ["connection-tokio"] } 
```
I believe this leads to having the default feature "async-std" set as well as "tokio". Right?
Is there a way to unset one if the other is set automatically and vice versa?
